Repository 1ezio/ietians-diary, pull requests merged in 2021-09, with the labels that each got.

#2 Created Readme, Updated gitignore
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  README.md
Labels: documentation

#5 Ietian's Diary from Scratch
  README.md
Labels: documentation

#14 added dependencies --card --firebase --mui
  app/build.gradle
  build.gradle
Labels: core, dependencies

#28 Bottom bar complete --with id
  app/src/main/res/drawable/ic_add_circle.xml
  app/src/main/res/drawable/ic_favorites.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_users.xml
  app/src/main/res/layout/activity_dashboard.xml
  app/src/main/res/layout/component_bottom_bar.xml
Labels: core, ui, dashboard

#29 Dashboard feature card
  app/src/main/res/drawable/feature_icon_bg.xml
  app/src/main/res/drawable/ic_square_next.xml
  app/src/main/res/drawable/ic_syllabus.xml
  app/src/main/res/font/poppins_light.xml
  app/src/main/res/font/poppins_medium.xml
  app/src/main/res/layout/component_feature_card.xml
  app/src/main/res/values/preloaded_fonts.xml
  app/src/main/res/values/strings.xml
Labels: core, ui, dashboard

#34 Roadmap Recyclerview
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/iet/ietians_diary/Adapters/RoadmapRecyclerViewAdapter.java
  app/src/main/java/com/iet/ietians_diary/Models/RoadmapModel.java
  app/src/main/java/com/iet/ietians_diary/Models/RoadmapModels.java
  app/src/main/java/com/iet/ietians_diary/RoadMap.java
  app/src/main/java/com/iet/ietians_diary/SignIn.java
  app/src/main/res/drawable/feature_roadmap_bg_blue.xml
  app/src/main/res/drawable/feature_roadmap_bg_green.xml
  app/src/main/res/drawable/feature_roadmap_bg_grey.xml
  app/src/main/res/drawable/feature_roadmap_bg_red.xml
  app/src/main/res/layout/activity_road_map.xml
  app/src/main/res/layout/component_roadmap_card.xml
Labels: core, ui, backend, roadmap

#35 New feature card created
  app/src/main/res/drawable/feature_circularimage_bg.xml
  app/src/main/res/drawable/feature_discussion_forum_bg_blue.xml
  app/src/main/res/drawable/feature_discussion_forum_button_bg.xml
  app/src/main/res/drawable/feature_discussion_forum_textview_bg.xml
  app/src/main/res/drawable/ic_messages.xml
  app/src/main/res/layout/component_allfeature_card.xml
  app/src/main/res/layout/component_card_new.xml
  app/src/main/res/layout/component_newfeature_card.xml
  app/src/main/res/raw/profile_image_1.png
  app/src/main/res/raw/profile_image_2.png
  app/src/main/res/raw/profile_image_3.png
  app/src/main/res/raw/profile_image_4.png
  app/src/main/res/values/strings.xml
Labels: core, ui

#37 Buttons added on dashboard and clickListener set with respective acti…
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/iet/ietians_diary/Dashboard.java
  app/src/main/java/com/iet/ietians_diary/Internship.java
  app/src/main/java/com/iet/ietians_diary/LabAssignment.java
  app/src/main/java/com/iet/ietians_diary/StudyMaterial.java
  app/src/main/java/com/iet/ietians_diary/Syllabus.java
  app/src/main/res/layout/activity_dashboard.xml
  app/src/main/res/layout/activity_internship.xml
  app/src/main/res/layout/activity_lab_assignment.xml
  app/src/main/res/layout/activity_study_material.xml
  app/src/main/res/layout/activity_syllabus.xml
Labels: core, ui
