Repository 1ezio/ietians-diary, pull requests merged in 2021-10, with the labels that each got.

#43 Added readme for IETian's Diary Fixes #42
  README.md
Labels: hacktoberfest-accepted

#41 string resources added
  app/src/main/java/com/iet/ietians_diary/SignIn.java
  app/src/main/res/values/strings.xml
Labels: hacktoberfest-accepted

#50 Deleted Unnecessary Files
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/iet/ietians_diary/Dashboard.java
  app/src/main/java/com/iet/ietians_diary/DashboardFragment.java
  app/src/main/java/com/iet/ietians_diary/RoadMap.java
  app/src/main/res/layout/activity_dashboard.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_road_map.xml
  app/src/main/res/layout/fragment_dashboard.xml
Labels: hacktoberfest-accepted

#47 unwanted raw resource files deleted
  app/src/main/res/raw/blue.png
  app/src/main/res/raw/green.png
  app/src/main/res/raw/logodummy.png
  app/src/main/res/raw/pink.png
  app/src/main/res/raw/textdummy.png
Labels: good first issue, hacktoberfest-accepted

#55 String resource created instead of hardcoded strings
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/layout/component_allfeature_card.xml
  app/src/main/res/layout/component_newfeature_card.xml
  app/src/main/res/layout/component_roadmap_card.xml
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/layout/fragment_roadmap.xml
  app/src/main/res/values/strings.xml
Labels: good first issue, hacktoberfest-accepted

#45 Next button corrected and disabled.
  app/src/main/java/com/iet/ietians_diary/SelectDetails.java
  app/src/main/res/drawable/ic_square_next_white.xml
  app/src/main/res/layout/activity_select_details.xml
Labels: hacktoberfest-accepted

#57 Readme contribution guidelines Fixes #53
  README.md
Labels: documentation, core, hacktoberfest-accepted

#56 IetiansDiary logo added in splash screen
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/raw/ietians_diary_logo.png
Labels: hacktoberfest-accepted

#59 readme updated Fixes #58
  README.md
Labels: documentation, hacktoberfest-accepted

#63 Logo added Fixes #61
  app/src/main/AndroidManifest.xml
  app/src/main/res/mipmap-hdpi/logo.png
  app/src/main/res/mipmap-mdpi/logo.png
  app/src/main/res/mipmap-xhdpi/logo.png
  app/src/main/res/mipmap-xxhdpi/logo.png
  app/src/main/res/mipmap-xxxhdpi/logo.png
Labels: hacktoberfest-accepted

#64 Added Top app bar to base activity, fetch google image
  app/build.gradle
  app/src/main/java/com/iet/ietians_diary/BaseActivity.java
  app/src/main/res/drawable/ic_notification_bell.xml
  app/src/main/res/layout/activity_base.xml
  app/src/main/res/layout/activity_select_details.xml
  app/src/main/res/layout/fragment_roadmap.xml
Labels: core, ui, hacktoberfest-accepted, backend

#65 typo and grammar error corrected
  README.md
Labels: documentation, hacktoberfest-accepted

#66 Name Updated From "ietians-diary" to "Ietians Diary"
  app/src/main/res/values/strings.xml
Labels: documentation, hacktoberfest-accepted

#67 Recyclerview added in dashboard fragment for allfeatures
  app/src/main/java/com/iet/ietians_diary/Adapters/DashboardAllFeaturesRecyclerViewAdapter.java
  app/src/main/java/com/iet/ietians_diary/DashboardFragment.java
  app/src/main/java/com/iet/ietians_diary/Models/DashboardAllFeaturesModel.java
  app/src/main/res/drawable/feature_icon_bg_blue.xml
  app/src/main/res/drawable/feature_icon_bg_green.xml
  app/src/main/res/drawable/feature_icon_bg_grey.xml
  app/src/main/res/drawable/feature_icon_bg_red.xml
  app/src/main/res/layout/component_allfeature_card.xml
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/values/strings.xml
Labels: core, ui, hacktoberfest-accepted

#71 Backend coneection
  app/DAVV Group_Final Result_Gen C & Elevate.xlsx
  app/src/main/java/com/iet/ietians_diary/Adapters/DashboardAllFeaturesRecyclerViewAdapter.java
  app/src/main/java/com/iet/ietians_diary/DashboardFragment.java
  app/src/main/java/com/iet/ietians_diary/SelectDetails.java
Labels: hacktoberfest-accepted

#73 updated android logo in README.md
  README.md
Labels: hacktoberfest-accepted

#74 errors resolved due to previous commit
  app/src/main/java/com/iet/ietians_diary/Adapters/DashboardAllFeaturesRecyclerViewAdapter.java
  app/src/main/java/com/iet/ietians_diary/SelectDetails.java
  app/src/main/res/layout/component_allfeature_card.xml
Labels: hacktoberfest-accepted

#75 Dashboard newfeatures recyclerview created
  app/src/main/java/com/iet/ietians_diary/Adapters/DashboardNewFeaturesRecyclerViewAdapter.java
  app/src/main/java/com/iet/ietians_diary/DashboardFragment.java
  app/src/main/java/com/iet/ietians_diary/Models/DashboardNewFeaturesModel.java
  app/src/main/res/drawable/feature_discussion_forum_bg_green.xml
  app/src/main/res/drawable/feature_discussion_forum_bg_grey.xml
  app/src/main/res/drawable/feature_discussion_forum_bg_red.xml
  app/src/main/res/drawable/feature_discussion_forum_textview_bg_blue.xml
  app/src/main/res/drawable/feature_discussion_forum_textview_bg_green.xml
  app/src/main/res/drawable/feature_discussion_forum_textview_bg_grey.xml
  app/src/main/res/drawable/feature_discussion_forum_textview_bg_red.xml
  app/src/main/res/drawable/ic_hello_hand.xml
  app/src/main/res/layout/component_newfeature_card.xml
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/values/strings.xml
Labels: hacktoberfest-accepted

#76 Added internet permission into AndroidManifest
  app/src/main/AndroidManifest.xml
  build.gradle
Labels: hacktoberfest-accepted

#77 toast duration reduced
  app/src/main/java/com/iet/ietians_diary/SelectDetails.java
  build.gradle
Labels: hacktoberfest-accepted
